#!/usr/bin/env sh

# shellcheck disable=SC3018
# shellcheck disable=SC3039

# Waits up to 15 seconds for a process to start
# Usage: wait_for_pid <pid file>
wait_for_pid() {
	let tout=15
	let cnt=tout
	while true; do
		if ! let cnt--; then echo "Failed to detect $1 after waiting $tout seconds"; return 1; fi
		[ -e "$1" ] && break
		sleep 1
	done
	let cnt=tout-cnt
	echo "PID $1 was found after waiting $cnt seconds!"
	return 0
}

# Waits up to 15 seconds for an interface to become available
# Usage: wait_for_if <iface>
wait_for_if() {
	let tout=15
	let cnt=tout
	while true; do
		if ! let cnt--; then echo "Interface $1 not found within $tout seconds"; return 1; fi
		[ -d "/sys/class/net/$1" ] && break
		sleep 1
	done
	let cnt=tout-cnt
	echo "Interface $1 was found after waiting $cnt seconds!"
	return 0
}

# Checks if the system has ntp
has_ntp() {
	test $(date "+%Y") -gt 2020
}

# Waits up to 15 seconds for network time synchronization
# Usage: wait_for_ntp
wait_for_ntp() {
	let tout=15
	let cnt=tout
	while true; do
		if ! let cnt--; then echo "Time not synchronized within $tout seconds"; return 1; fi
		has_ntp && break
		sleep 1
	done
	let cnt=tout-cnt
	echo "Time synchronized after waiting $cnt seconds!"
	return 0
}

# Waits n seconds for user to cancel
# wait_for_cancel [time default=5 seconds]
wait_for_cancel() {
	let tout=6
	[ $# -ge 1 ] && let "tout=$1+1"
	while let tout--; do
		echo -ne "\rPress any key to cancel, $tout seconds remaining..."
		if read -n 1 -s -t 1; then echo; return 1; fi
	done
	echo
	return 0
}
