#!/usr/bin/env sh

# shellcheck disable=SC3018
# shellcheck disable=SC3039

# Waits up to 15 seconds for a process to start
# Usage: wait_for_pid <pid file>
wait_for_pid() {
	let tout=15
	let cnt=tout
	while true; do
		if ! let cnt--; then echo "Failed to detect $1 after waiting $tout seconds"; return 1; fi
		[ -e "$1" ] && break
		sleep 1
	done
	let cnt=tout-cnt
	echo "PID $1 was found after waiting $cnt seconds!"
	return 0
}

# Waits up to 15 seconds for an interface to become available
# Usage: wait_for_if <iface>
wait_for_if() {
	let tout=15
	let cnt=tout
	while true; do
		if ! let cnt--; then echo "Interface $1 not found within $tout seconds"; return 1; fi
		[ -d "/sys/class/net/$1" ] && break
		sleep 1
	done
	let cnt=tout-cnt
	echo "Interface $1 was found after waiting $cnt seconds!"
	return 0
}
