# Enable WiFi
CONFIG_CFG80211=y
CONFIG_CFG80211_WEXT=y
CONFIG_MAC80211=y
CONFIG_WLAN=y

# Enable Broadcom BRCM FMAC driver
CONFIG_NET_VENDOR_BROADCOM=y
CONFIG_BRCMFMAC=m
CONFIG_BRCMFMAC_SDIO=y
CONFIG_BRCMSMAC=m
CONFIG_BRCMUTIL=m

# Enable RF switches
CONFIG_RFKILL=y
CONFIG_RFKILL_GPIO=y
