CONFIG_STAGING=y
CONFIG_SPI=y
CONFIG_FB=y
CONFIG_FB_DEVICE=y
CONFIG_BACKLIGHT_CLASS_DEVICE=y
CONFIG_BACKLIGHT_GPIO=y
CONFIG_FB_TFT=y
CONFIG_FB_TFT_ST7735R=y
CONFIG_FONTS=y
# CONFIG_FONT_8x16 is not set
CONFIG_FONT_ACORN_8x8=y
CONFIG_FRAMEBUFFER_CONSOLE=y
