#!/usr/bin/env bash

dir="$(dirname "${BASH_SOURCE}")"

templates="${dir}/templates/dts"
inp_fname="${templates}/fpga-template.dtso"
out_fname="${dir}/dts/xilinx/fpga.dtso"

echo -e "// =================================================================================="   >"$out_fname"
echo -e "//  Autogenerated from $fname by $0 on $(date)"                                          >>"$out_fname"
echo -e "// ==================================================================================\n" >>"$out_fname"

IFS=''
let int=0
while read line; do
	if echo "$line" | grep -qE '^\s*#START_INTERRUPT_CNT\s+[A-Za-z0-9]+'; then
		int="$(echo "$line" | sed 's/^.\+START_INTERRUPT_CNT//g' | awk -F' ' '{print $1}' | tr '[:upper:]' '[:lower:]')"
	elif echo "$line" | grep -qE '^\s*#INSERT_DISPLAY\s+[A-Za-z0-9]+'; then
		num="$(echo "$line" | sed 's/^.\+INSERT_DISPLAY//g' | awk -F' ' '{print $1}' | tr '[:upper:]' '[:lower:]')"
		cat "${templates}/display-template.dtso" | \
			HEX="$num" NUM=$((0x$num)) INT="$int" envsubst \
			>>"$out_fname"
		let int=int+1
	else
		echo "$line" >>"$out_fname"
	fi
done < "$inp_fname"
