#!/usr/bin/sh

BUILDROOT_VERSION="2025.02.x"
BUILDROOT_REPO="buildroot"
BUILDROOT_URL="https://github.com/buildroot/${BUILDROOT_REPO}.git"

DEPLOY_USER="root"
DEPLOY_FILE="images/sdcard.img"
DEPLOY_LOCATION="/tmp/sdcard.img"
DEPLOY_COMMAND="upgrade"
