#!/usr/bin/env bash

usage() {
	echo "Usage: $0 <operation>"
	echo "Operations:"
	echo "  setup <boards>      - Sets up builds for the given boards"
	echo "  build <boards>      - Builds the given boards"
	echo "  source <boards>     - Sources files for the given boards"
	echo "  deploy <boards>     - Runs deployment for the given boards"
	echo "  shellcheck [format] - Runs shellcheck on all scripts with a specialized format"
	echo "  list                - Lists all available boards"
	echo "  help                - Shows this menu"
}

echo_cmd() { echo "$@"; "$@"; }

init_board() {
	if [ ! -f "bsps/${1}.bsp" ]; then
		echo -e "\e[1;31mBSP $1 does not exist!\e[0m"
		exit 1
	fi

	BSP_NAME=""
	DEPLOY_TO=""
	BUILDROOT_VERSION=""

	. "bsps/defaults"
	. "bsps/${1}.bsp"

	local BUILDROOT_STR="${BUILDROOT_REPO}-${BUILDROOT_VERSION}"
	BUILD_DIR="${BUILDS_DIR}/${1}"
	BUILDROOT_DIR="${BUILDS_DIR}/${BUILDROOT_STR}"
	BR2_EXTERNAL="$PWD"

	set +u
	[ -z "$BSP_NAME" ] && \
		BSP_NAME="$1";

	if [ -z "$BR2_DL_DIR" ]; then
		mkdir -p "${BUILDS_DIR}"
		export BR2_DL_DIR="$(realpath "${BUILDS_DIR}/dl")"
		mkdir -p "${BR2_DL_DIR}"
		echo -e "\e[1;33mNo global DL dir is setup, created/using a local one at $BR2_DL_DIR\e[0m"
	fi
	set -u

	if [ ! -d "${BUILDROOT_DIR}/.git" ]; then
		echo -e "\e[1;33mCloning buildroot since it didn't already exist\e[0m"
		git clone --single-branch "${BUILDROOT_URL}" --branch "${BUILDROOT_VERSION}" "${BUILDROOT_DIR}"
		echo -e "\e[1;32mCloned most recent buildroot into ${BUILDROOT_STR}\e[0m"
	else
		local LWD="$PWD"
		cd "$BUILDROOT_DIR"
		fetch_epoch="$(stat -c %Y ".git/FETCH_HEAD" || echo 0)"
		cur_epoch="$(date +%s)"
		too_old="$(echo "(${cur_epoch} - ${fetch_epoch}) > 86400" | bc)"
		if [ $too_old -ne 0 ]; then
			echo -e "\e[1;33mBuildroot for ${BUILDROOT_STR} was over a day old!\e[0m"
			echo -e "\e[1;33mFetching latest buildroot for ${BUILDROOT_STR}!\e[0m"
			git fetch
			git checkout "${BUILDROOT_VERSION}"
			git pull
			echo -e "\e[1;32mBuildroot ${BUILDROOT_STR} has been updated!\e[0m"
		else
			echo -e "\e[1;32mBuildroot ${BUILDROOT_STR} is up to date!\e[0m"
		fi
		cd "$LWD"
	fi
}

setup_board() {
	init_board "$1"
	echo -e "\e[1;33mSetting up BSP $1\e[0m"

	mkdir -p "${BUILD_DIR}/host" "${BUILD_DIR}/build" "${BUILD_DIR}/target"
	rm -rf "${BUILD_DIR}/.config" "${BUILD_DIR}/.config.old"

	DEF_CONFIG="${BUILD_DIR}/${BSP_NAME}_defconfig"
	GEN_CONFIG="${BUILD_DIR}/${BSP_NAME}_genconfig"
	cp "configs/${BSP_CONFIG}" "$GEN_CONFIG"

	printf "BR2_DEFCONFIG=\"%s\"\n"    "$(realpath "$DEF_CONFIG")"   >>"$GEN_CONFIG"
	printf "BR2_BR2_EXTERNAL=\"%s\"\n" "$(realpath "$BR2_EXTERNAL")" >>"$GEN_CONFIG"
	printf "BR2_DL_DIR=\"%s\"\n"       "$(realpath "$BR2_DL_DIR")"   >>"$GEN_CONFIG"

	echo_cmd ./gencfg.py "$DEF_CONFIG" "$GEN_CONFIG" \
		"${PWD}/configs" "${BUILDROOT_DIR}/configs"

	make -C "$(realpath "$BUILDROOT_DIR")" \
		O="$(realpath "$BUILD_DIR")" \
		BR2_DEFCONFIG="$(realpath "$DEF_CONFIG")" \
		BR2_EXTERNAL="${PWD}" \
		defconfig

	echo -e "\e[1;32mSetup completed!\e[0m"
}

build_board() {
	bsp="$1"
	init_board "$bsp"
	shift 1
	echo -e "\e[1;33mBuilding BSP $BSP_NAME\e[0m"

	log="$(realpath "$BUILD_DIR")/build.log"
	make -C "$(realpath "$BUILDROOT_DIR")" \
		O="$(realpath "$BUILD_DIR")" \
		"$@" 2>&1 \
        | tee -a "$log" \
        | grep '>>>' --line-buffered --color=never \
		| sed -u "s/>>>/[${bsp}: $@]/g" \
		|| (err="$?"; tail -n 250 "$log"; exit "$err")

	echo -e "\e[1;32mBuild completed!\e[0m"
}

shellcheck_all() {
	local check=()
	[ -n "$1" ] && check=("--format=$1")
	mapfile -t check < <(echo "${check[@]}" && rg -l '^#!.+sh$')
	shellcheck "${check[@]}"
}

if [ $# -lt 1 ]; then usage; exit 1; fi

set -euo pipefail

ORIG_DIR="$PWD"
BSP_DIR="$(dirname "${BASH_SOURCE}")"
cd "$BSP_DIR"

set +u
[ -z "$BUILDS_DIR" ] && export BUILDS_DIR="../builds"
set -u

case "$1" in
	setup)  shift 1; for f in "$@"; do setup_board "$f"; done ;;
	source) shift 1; for f in "$@"; do build_board "$f" "source"; done ;;
	build)  shift 1; for f in "$@"; do build_board "$f" "all"; done ;;
	deploy) shift 1; for f in "$@"; do build_board "$f" "deploy"; done ;;
	list)   shift 1;
		cmd=("basename" "{}" ".bsp")
		set +u; case "$1" in
			p|prod|production) cmd=("bash" "-c" ". {}; if [ -n \"\$DEPLOY_TO\" ]; then basename {} .bsp; fi") ;;
			d|dev|develop|development) cmd=("bash" "-c" ". {}; if [ -z \"\$DEPLOY_TO\" ]; then basename {} .bsp; fi") ;;
		esac; set -u; cmd+=(';')
		for bsp in $(fd '^[\w-]+\.bsp$' bsps/ -x "${cmd[@]}" | sort); do
			DEPLOY_TO="n/a"
			BUILDROOT_VERSION="error"
			. "bsps/defaults"
			. "bsps/${bsp}.bsp"
			broot="$BUILDROOT_VERSION"
			printf "%-20s %-11s %-15s\n" "$bsp" "$broot" "$DEPLOY_TO"
		done
		;;
	shellcheck) shift 1; set +u; shellcheck_all "$1" ;;
	help)  usage ;;
	*)
		usage
		exit 1
		;;
esac

cd "$ORIG_DIR"

exit 0
