#!/usr/bin/env bash

usage() {
	echo "Usage: $0 <operation>"
	echo "Operations:"
	echo "  setup <board> - Sets up a build for a given board"
	echo "  build <board> - Builds the given board"
	echo "  list          - Lists all available boards"
	echo "  help          - Shows this menu"
}

echo_cmd() { echo "$@"; "$@"; }

init_board() {
	if [ ! -f "bsps/${1}.bsp" ]; then
		echo -e "\e[1;31mBSP $1 does not exist!\e[0m"
		exit 1
	fi

	. "bsps/defaults"
	. "bsps/${1}.bsp"

	local BUILDROOT_STR="${BUILDROOT_REPO}-${BUILDROOT_VERSION}"
	BUILDS_DIR="../builds"
	BUILD_DIR="${BUILDS_DIR}/${1}"
	BUILDROOT_DIR="${BUILDS_DIR}/${BUILDROOT_STR}"
	BR2_EXTERNAL="$PWD"
	set +u; [ -z "$BSP_NAME" ] && BSP_NAME="$1"; set -u

	set +u
	if [ -z "$BR2_DL_DIR" ]; then
		BR2_DL_DIR="$(realpath "${BUILDS_DIR}/dl")"
		mkdir -p "$BR2_DL_DIR"
		echo -e "\e[1;33mNo global DL dir is setup, created/using a local one at $BR2_DL_DIR\e[0m"
	fi
	set -u

	if [ ! -d "${BUILDROOT_DIR}/.git" ]; then
		echo -e "\e[1;33mCloning buildroot since it didn't already exist\e[0m"
		git clone "${BUILDROOT_URL}" "${BUILDROOT_DIR}"
		echo -e "\e[1;32mCloned most recent buildroot into ${BUILDROOT_STR}\e[0m"
	else
		local LWD="$PWD"
		cd "$BUILDROOT_DIR"
		echo -e "\e[1;33mFetching latest buildroot for ${BUILDROOT_STR}\e[0m"
		git fetch
		git checkout "${BUILDROOT_VERSION}"
		git pull
		echo -e "\e[1;32mBuildroot ${BUILDROOT_STR} has been updated!\e[0m"
		cd "$LWD"
	fi
}

setup_board() {
	init_board "$1"
	echo -e "\e[1;33mSetting up BSP $1\e[0m"

	mkdir -p "${BUILD_DIR}/host" "${BUILD_DIR}/build" "${BUILD_DIR}/target"
	rm -rf "${BUILD_DIR}/.config" "${BUILD_DIR}/.config.old"

	DEF_CONFIG="${BUILD_DIR}/${BSP_NAME}_defconfig"
	GEN_CONFIG="${BUILD_DIR}/${BSP_NAME}_genconfig"
	cp "configs/${BSP_CONFIG}" "$GEN_CONFIG"

	printf "BR2_DEFCONFIG=\"%s\"\n"    "$(realpath "$DEF_CONFIG")"   >>"$GEN_CONFIG"
	printf "BR2_BR2_EXTERNAL=\"%s\"\n" "$(realpath "$BR2_EXTERNAL")" >>"$GEN_CONFIG"
	printf "BR2_DL_DIR=\"%s\"\n"       "$(realpath "$BR2_DL_DIR")"   >>"$GEN_CONFIG"

	echo_cmd ./gencfg.py "$DEF_CONFIG" "$GEN_CONFIG" \
		"${PWD}/configs" "${BUILDROOT_DIR}/configs"

	make -C "$(realpath "$BUILDROOT_DIR")" \
		O="$(realpath "$BUILD_DIR")" \
		BR2_DEFCONFIG="$(realpath "$DEF_CONFIG")" \
		BR2_EXTERNAL="${PWD}" \
		defconfig

	echo -e "\e[1;32mSetup completed!\e[0m"
}

build_board() {
	setup_board "$1"
	echo -e "\e[1;33mBuilding BSP $BSP_NAME\e[0m"

	make -C "$(realpath "$BUILDROOT_DIR")" \
		O="$(realpath "$BUILD_DIR")" \
		all

	echo -e "\e[1;32mBuild completed!\e[0m"
}

if [ $# -lt 1 ]; then usage; exit 1; fi

set -euo pipefail

ORIG_DIR="$PWD"
BSP_DIR="$(dirname "${BASH_SOURCE}")"
cd "$BSP_DIR"

case "$1" in
	setup)
		shift 1
		setup_board "$1"
		;;
	build)
		shift 1
		build_board "$1"
		;;
	list)
		fd '^[\w-]+\.bsp$' bsps/ -x basename {} ".bsp" \;
		;;
	help)
		usage
		;;
	*)
		usage
		exit 1
		;;
esac

cd "$ORIG_DIR"

exit 0
