#!/usr/bin/env python3

import os

def parse_config(cfg_tbl, gencfg, sources, depth):
	if depth < 0:
		print("\u001B[1;31mMaximum depth reached, recursive config detected!\u001B[0m")
		return False

	for line in gencfg:
		# Ignore whitespace only lines / empty lines
		line = line.strip()
		if len(line) < 1:
			pass
		# Handle includes
		elif line.startswith("#include "):
			cfg_fname = find_config(sources, line[9:].strip("\""))

			if cfg_fname == None:
				return False

			with open(cfg_fname, 'r') as icfg:
				print("\u001B[1;32mParsing included config: %s\u001B[0m" % cfg_fname)
				if parse_config(cfg_tbl, icfg, sources, depth - 1):
					print("\u001B[1;32mSuccessfully parsed config: %s\u001B[0m" % cfg_fname)
				else:
					return False
		# Handle comments
		elif line.startswith("#"):
			pass
		# Handle config entries
		elif '=' in line:
			pos = line.index('=')
			key = line[:pos]
			val = line[pos+1:]
			if key in cfg_tbl:
				print("\u001B[1;33mOverwriting \"%s\" with \"%s\" (was \"%s\")\u001B[0m" % (key, val, cfg_tbl[key]))
			print("%s set to %s" % (key, val))
			cfg_tbl[key] = val
		# Handle invalid lines
		else:
			print("\u001B[1;31mInvalid entry in config: \"%s\"\u001B[0m" % (line))
			return False

	return True

def find_config(sources, fname):
	for src in sources:
		ls = os.listdir(src)
		for name in ls:
			if fname == name:
				if not src.endswith("/"):
					src += "/"
				return src + fname

	print("\u001B[1;31mFailed to find config %s!\u001B[0m" % fname)
	return None

def main(defcfg_fname, gencfg_fname, src_dnames):
	cfg_tbl = {}
	with open(gencfg_fname, 'r') as gencfg:
		with open(defcfg_fname, 'w') as defcfg:
			if parse_config(cfg_tbl, gencfg, src_dnames, 100):
				print("\u001B[1;33mConfigs parsed, writing to file!\u001B[0m")
				defcfg.write("# This defconfig was auto-generated by %s\n" % (argv[0]))
				defcfg.write("# DO NOT MODIFY\n")
				for key, val in cfg_tbl.items():
					defcfg.write("%s=%s\n" % (key, val))
			else:
				exit(1)

def usage(ec=1):
	from sys import exit
	print("Usage: %s <defconfig> <genconfig> <sources ...>" % argv[0])
	print("  defconfig - The buildroot defconfig to output")
	print("  genconfig - The input genconfig with includes")
	print("  sources   - Where to find included configs, at least 1 is reguired")
	print("              best to use $BSP_EXTERNAL/configs and $BUILDROOT_DIR/configs")
	print("")
	exit(ec)

if __name__ == "__main__":
	from sys import argv

	if len(argv) < 4:
		print("\u001B[1;31mNot enough arguments provided!\u001B[0m\n")
		usage(1)

	main(argv[1], argv[2], argv[3:])


