#!/usr/bin/env python3

import os

def should_ignore_key(key, only):
	if only != None:
		if key != only:
			return True
		else:
			print("\u001B[1;33mGrabbing specific config key %s\u001B[0m" % (key))
	return False

def handle_include(cfg_tbl, sources, depth, only, line):
	grab = None
	pos = None

	if line.startswith("#include_only "):
		line = line[14:]
		pos = line.index(' ')
		grab = line[:pos].strip()
		line = line[pos:].strip()
		print("\u001B[1;35mChecking config %s for %s\u001B[0m" % (line, grab))
	elif line.startswith("#include "):
		line = line[9:].strip()

	if line == None:
		print("\u001B[1;31mInvalid include!\u001B[0m")

	cfg_fname = find_config(sources, line.strip("\""))
	if cfg_fname == None:
		return False

	with open(cfg_fname, 'r') as icfg:
		print("\u001B[1;32mParsing included config: %s\u001B[0m" % cfg_fname)
		if parse_config(cfg_tbl, icfg, sources, depth - 1, grab):
			print("\u001B[1;32mSuccessfully parsed config: %s\u001B[0m" % cfg_fname)
		else:
			return False

	return True

def parse_config(cfg_tbl, gencfg, sources, depth, only=None):
	if depth < 0:
		print("\u001B[1;31mMaximum depth reached, recursive config detected!\u001B[0m")
		return False

	for line in gencfg:
		# Ignore whitespace only lines / empty lines
		line = line.strip()
		if len(line) < 1:
			pass
		# Handle config specific includes
		# Handle includes
		elif line.startswith("#include"):
			if not handle_include(cfg_tbl, sources, depth, only, line):
				return False
		# Handle comments
		elif line.startswith("#"):
			if line.endswith(" is not set"):
				arr = line[2:].split(' ')
				if len(arr) != 5:
					pass

				key = arr[0]
				if should_ignore_key(key, only):
					continue

				cfg_tbl[key] = None
				print("\u001B[1;33mUnsetting %s\u001B[0m" % (key))
			else:
				pass
		# Handle config entries
		elif '=' in line:
			pos = line.index('=')
			if line[pos - 1] == '+':
				key = line[:pos-1]

				val = line[pos+1:]
				if key in cfg_tbl:
					print("\u001B[1;33mAppending %s to \"%s\"\u001B[0m" % (val, key))
					cfg_tbl[key] = cfg_tbl[key].rstrip("\"\'") + " " + val.lstrip("\"\'");
				else:
					print("\u001b[1;31mWarning, %s was not set, will set to %s\u001b[0m" % (key, val))
					cfg_tbl[key] = val
			else:
				key = line[:pos]
				if should_ignore_key(key, only):
					continue

				val = line[pos+1:]
				if key in cfg_tbl:
					print("\u001B[1;33mOverwriting \"%s\" with \"%s\" (was \"%s\")\u001B[0m" % (key, val, cfg_tbl[key]))
				print("%s set to %s" % (key, val))
				cfg_tbl[key] = val
		# Handle invalid lines
		else:
			print("\u001B[1;31mInvalid entry in config: \"%s\"\u001B[0m" % (line))
			return False

	return True

def find_config(sources, fname):
	for src in sources:
		ls = os.listdir(src)
		for name in ls:
			if fname == name:
				if not src.endswith("/"):
					src += "/"
				return src + fname

	print("\u001B[1;31mFailed to find config %s!\u001B[0m" % fname)
	return None

def main(defcfg_fname, gencfg_fname, src_dnames):
	cfg_tbl = {}
	with open(gencfg_fname, 'r') as gencfg:
		with open(defcfg_fname, 'w') as defcfg:
			if parse_config(cfg_tbl, gencfg, src_dnames, 100):
				print("\u001B[1;33mConfigs parsed, writing to file!\u001B[0m")
				defcfg.write("# This defconfig was auto-generated by %s\n" % (argv[0]))
				defcfg.write("# DO NOT MODIFY\n")
				for key, val in cfg_tbl.items():
					if val == None:
						defcfg.write("# %s is not set\n" % (key))
					else:
						defcfg.write("%s=%s\n" % (key, val))
			else:
				exit(1)

def usage(ec=1):
	from sys import exit
	print("Usage: %s <defconfig> <genconfig> <sources ...>" % argv[0])
	print("  defconfig - The buildroot defconfig to output")
	print("  genconfig - The input genconfig with includes")
	print("  sources   - Where to find included configs, at least 1 is reguired")
	print("              best to use $BSP_EXTERNAL/configs and $BUILDROOT_DIR/configs")
	print("")
	exit(ec)

if __name__ == "__main__":
	from sys import argv

	if len(argv) < 4:
		print("\u001B[1;31mNot enough arguments provided!\u001B[0m\n")
		usage(1)

	main(argv[1], argv[2], argv[3:])


