#!/usr/bin/env sh

RTC_DEV="/dev/rtc0"

if [ ! -c "$RTC_DEV" ]; then
	echo "HW Clock daemon not running, no hardware clock"
	exit 1
fi

set -e

daemon() {
	echo "HW Clock daemon started!"
	while true; do
		sleep 86400
		hwclock -w -f "$RTC_DEV"
		echo "HW clock updated with system time"
	done
	echo "HW Clock daemon stopped!"
}

PID_FILE="/var/run/hwclock.pid"

case "$1" in
	start)
		[ -f "$PID_FILE" ] && "$0" stop
		daemon &
		echo "$!" >"$PID_FILE"
		;;
	stop)
		if [ -f "$PID_FILE" ]; then
			kill -SIGINT "$(cat "$PID_FILE")" || echo "Failed to stop process, removing pid file anyways"
			rm -f "$PID_FILE"
		else
			echo "HW clock daemon not running!"
		fi
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	*)
		echo "Usage: $0 <start/stop/restart>"
		exit 1
		;;
esac

