#!/usr/bin/env sh

case "$1" in
	start)
		mount -t configfs configfs /sys/kernel/config
		if cat /proc/cmdline | grep -q 'qemu=1'; then
			echo -e "\e[1;33mNot loading FPGA since were running in QEMU!\e[0m"
		else
			echo -e "\e[1;33mLoading FPGA... \e[0m"
			mkdir /sys/kernel/config/device-tree/overlays/fpga
			if cat /lib/firmware/fpga.dtbo >/sys/kernel/config/device-tree/overlays/fpga/dtbo; then
				echo -e "\e[1;32mFPGA loaded!\e[0m"
			else
				echo -e "\e[1;31mFPGA failed to load!\e[0m"
			fi
		fi
		;;
	stop)
		rm -rf /sys/kernel/config/device-tree/overlays/fpga
		;;
	restart)
		"$0" start
		"$0" stop
		;;
	*)
		echo "usage: $0 <start/stop/restart>"
		exit 1
		;;
esac
