BR2_LINUX_KERNEL_CUSTOM_VERSION=y
BR2_LINUX_KERNEL_CUSTOM_VERSION_VALUE="6.12.57"
BR2_KERNEL_HEADERS_6_12=y

BR2_ROOTFS_OVERLAY="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/skeleton"
BR2_ROOTFS_DEVICE_TABLE="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/skeleton.txt"
BR2_ROOTFS_USERS_TABLES="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/users.txt"
BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_MDEV=y

BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES+="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/linux-headless.frag"

BR2_PACKAGE_BUSYBOX_CONFIG_FRAGMENT_FILES="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/busybox.frag"

BR2_GLOBAL_PATCH_DIR="$(BR2_EXTERNAL_JLBSP_PATH)/patches"

BR2_CCACHE=y
BR2_CCACHE_USE_BASEDIR=y

BR2_PACKAGE_FD=y
BR2_PACKAGE_FILE=y
BR2_PACKAGE_HTOP=y
BR2_PACKAGE_I2C_TOOLS=y
BR2_PACKAGE_IPERF3=y
BR2_PACKAGE_IPTABLES=y
BR2_PACKAGE_LIBEVENT=y
BR2_PACKAGE_LIBGPIOD2=y
BR2_PACKAGE_LIBGPIOD2_TOOLS=y
BR2_PACKAGE_LSHW=y
BR2_PACKAGE_MAKE=y
BR2_PACKAGE_NANO=y
BR2_PACKAGE_NCURSES=y
BR2_PACKAGE_NETCAT_OPENBSD=y
BR2_PACKAGE_NMAP=y
BR2_PACKAGE_OPENSSL=y
BR2_PACKAGE_OPENSSH=y
BR2_PACKAGE_OPENSSH_CLIENT=y
BR2_PACKAGE_OPENSSH_SERVER=y
BR2_PACKAGE_PARTED=y
BR2_PACKAGE_PICOCOM=y
BR2_PACKAGE_PIGZ=y
BR2_PACKAGE_RIPGREP=y
BR2_PACKAGE_TMUX=y
BR2_PACKAGE_VIM=y
BR2_PACKAGE_WHICH=y
BR2_PACKAGE_ZLIB=y
