BR2_LINUX_KERNEL_LATEST_VERSION=y
BR2_KERNEL_HEADERS_6_12=y

BR2_ROOTFS_OVERLAY="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/skeleton"
BR2_ROOTFS_DEVICE_TABLE="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/skeleton.txt"
BR2_ROOTFS_USERS_TABLES="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/users.txt"
BR2_ROOTFS_DEVICE_CREATION_DYNAMIC_MDEV=y
BR2_TARGET_ROOTFS_EXT2_SIZE="150M"

BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES+="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/linux/headless.frag"

BR2_PACKAGE_BUSYBOX_CONFIG_FRAGMENT_FILES="$(BR2_EXTERNAL_JLBSP_PATH)/board/common/busybox.frag"

BR2_GLOBAL_PATCH_DIR+="$(BR2_EXTERNAL_JLBSP_PATH)/patches"

BR2_CCACHE=y
BR2_CCACHE_USE_BASEDIR=y

BR2_TARGET_TZ_INFO=y
BR2_TARGET_LOCALTIME="America/Chicago"

BR2_PACKAGE_DOSFSTOOLS=y
BR2_PACKAGE_DOSFSTOOLS_FSCK_FAT=y
BR2_PACKAGE_E2FSPROGS=y
BR2_PACKAGE_E2FSPROGS_FSCK=y
BR2_PACKAGE_FILE=y
BR2_PACKAGE_HTOP=y
BR2_PACKAGE_NANO=y
BR2_PACKAGE_NCURSES=y
BR2_PACKAGE_NTP=y
BR2_PACKAGE_NTP_NTPD=y
BR2_PACKAGE_NTP_NTPQ=y
BR2_PACKAGE_OPENSSH=y
BR2_PACKAGE_OPENSSH_SERVER=y
BR2_PACKAGE_WHICH=y
BR2_PACKAGE_XZ=y
BR2_PACKAGE_BATS_ASSERT=y
BR2_PACKAGE_BATS_FILE=y
BR2_PACKAGE_BATS_SUPPORT=y
BR2_PACKAGE_BATS_CORE=y

# Include dev tools in all builds by default
# as they can always be removed later via an unclude
#include dev-tools.frag
