#include common.frag

BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES+="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/linux-minimal.frag"
BR2_LINUX_KERNEL_CUSTOM_DTS_DIR="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/dts"

BR2_TOOLCHAIN_BUILDROOT=y
BR2_TOOLCHAIN_BUILDROOT_USE_SSP=y
BR2_UCLIBC_INSTALL_UTILS=y
BR2_KERNEL_HEADERS_6_12=y

BR2_ROOTFS_OVERLAY+="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/skeleton"
BR2_ROOTFS_DEVICE_TABLE+="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/skeleton.txt"
