#include common.frag

# Custom kernel here since the rpi is special
# BR2_LINUX_KERNEL_LATEST_VERSION is not set
BR2_LINUX_KERNEL_CUSTOM_TARBALL=y

BR2_LINUX_KERNEL_CONFIG_FRAGMENT_FILES+="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/linux-minimal.frag"

BR2_TOOLCHAIN_BUILDROOT=y
BR2_TOOLCHAIN_BUILDROOT_USE_SSP=y
BR2_UCLIBC_INSTALL_UTILS=y
BR2_KERNEL_HEADERS_6_12=y

# These need set if I ever add anything pi specific to the skeleton
# BR2_ROOTFS_OVERLAY+="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/skeleton"
# BR2_ROOTFS_DEVICE_TABLE+="$(BR2_EXTERNAL_JLBSP_PATH)/board/rpi/skeleton.txt"

BR2_PACKAGE_JL_SECRET_KEYS=y
BR2_PACKAGE_JL_SECRET_KEYS_DEV=y
