# .github/workflow/build.yml

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  checks:
    runs-on: linux-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Shellcheck
        run: ./bsp shellcheck

  build:
    runs-on: linux-amd64
    env:
      PROD_BSPS: ntp tdisp led-alarm wg-proxy
      DEPLOY_BSPS: ntp tdisp led-alarm
      RPI_DEV_BSPS: rpi2-dev rpi5-dev rpi0w-dev
      MISC_DEV_BSPS: lepotato-dev orangepi-zero3-dev radxa0-3e-dev
      SSH_OPTS: -i /home/act_runner/.ssh/id_ed25519 -oBatchMode=yes
      BR2_DL_DIR: /opt/act-runner-dl
      BR2_CCACHE_DIR: /opt/act-runner/ccache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Clean ccache
        run: |
            rm -rf "${BR2_CCACHE_DIR}"
            mkdir "${BR2_CCACHE_DIR}"

# Build production bsps
      - name: Setup production BSPs
        timeout: 30
        run: support/pipeline.sh setup $PROD_BSPS

      - name: Source production BSPs
        timeout: 180
        run: support/pipeline.sh source $PROD_BSPS

      - name: Build production BSPs
        timeout: 180
        run: support/pipeline.sh build $PROD_BSPS

      - name: Deploy production BSPs
        timeout: 30
        run: support/pipeline.sh deploy $DEPLOY_BSPS

# Setup developmental bsps
      - name: Setup all development BSPs
        timeout: 30
        run: support/pipeline.sh setup $RPI_DEV_BSPS $MISC_DEV_BSPS

      - name: Notify when finished
        run: support/pipeline.sh notify "production"

# Build developmental rpi based BSPs
      - name: Source rpi based development BSPs
        timeout: 60
        run: support/pipeline.sh source $RPI_DEV_BSPS

      - name: Build rpi based development BSPs
        timeout: 300
        run: support/pipeline.sh build $RPI_DEV_BSPS

      - name: Notify when finished
        run: support/pipeline.sh notify "rpi development"

# Build developmental non-rpi based BSPs

      - name: Source non-rpi based development BSPs
        timeout: 60
        run: support/pipeline.sh source $MISC_DEV_BSPS

      - name: Build non-rpi based development BSPs
        timeout: 300
        run: support/pipeline.sh build $MISC_DEV_BSPS

      - name: Notify when finished
        run: support/pipeline.sh notify "miscellaneous development"

      - name: Cleanup DL dir
        run: find "${BR2_DL_DIR}" -atime +30 -exec rm -v "{}" \;
