#!/usr/bin/env sh

PID_FILE="/var/run/led-alarm.pid"
CONF_FILE="/var/run/led-alarm.conf"

case "$1" in
	start)
		if [ -f "$PID_FILE" ]; then
			"$0" stop;
		fi
		/usr/bin/led-alarm -c "$CONF_FILE" -p "$PID_FILE" &
		;;
	stop)
		if [ -f "$PID_FILE" ]; then
			kill -SIGINT "$(cat $PID_FILE)"
			rm -f "$PID_FILE"
		fi
		;;
	reload)
		if [ -f "$PID_FILE" ]; then
			kill -SIGUSR1 "$(cat $PID_FILE)"
		else
			echo "Cannot reload if not started / running!"
			exit 1
		fi
		;;
	restart)
		"$0" stop
		"$0" start
		;;
esac
