CONFIG_CFG80211=y
CONFIG_CFG80211_WEXT=y
CONFIG_MAC80211=y
CONFIG_WLAN=y
CONFIG_NET_VENDOR_BROADCOM=y/
CONFIG_BRCMFMAC=m
CONFIG_BRCMFMAC_SDIO=y
CONFIG_BRCMSMAC=y
CONFIG_BRCMUTIL=y
CONFIG_RFKILL=y
CONFIG_RFKILL_GPIO=y

# CONFIG_USB_SUPPORT is not set

# Disable the chinese backdoors / hardware crypto drivers
# CONFIG_CRYPTO_DEV_ALLWINNER is not set
# CONFIG_CRYPTO_DEV_SUN4I_SS is not set
# CONFIG_CRYPTO_DEV_SUN8I_CE is not set
# CONFIG_CRYPTO_DEV_SUN8I_SS is not set
