bindaddress 0.0.0.0
bindcmdaddress 127.0.0.1
allow all

refclock SHM 0 offset 0.156 refid NMEA
refclock PPS /dev/pps0 lock NMEA refid GPS prefer local

server 0.us.pool.ntp.org iburst
server time-a-g.nist.gov iburst
server time-a-wwv.nist.gov iburst
server time-a-b.nist.gov iburst
server time.google.com iburst
server time.cloudflare.com iburst
server time.aws.com iburst

leapsecmode slew
maxslewrate 1000
smoothtime 400 0.001024 leaponly
makestep 1.0 -1
