###### My Changes ######

#server time-a-b.nist.gov iburst
#server time-a-g.nist.gov

local stratum 1

refclock SHM 0 offset 0.436 delay 0.2 refid NMEA noselect
refclock PPS /dev/pps0 lock NMEA refid GPS prefer

allow 192.168.0.0/21

okeyfile /var/lib/ntp/ntp.kets
ntsdumpdir /var/lib/ntp/nts
maxupdateskew 10.0
rtcsync
makestep 1 3
leapsectz right/UTC

driftfile /var/lib/ntp/ntp.drift
logfile /var/log/ntp.log
