Section "Device"
	Identifier "fb"
	Driver     "fbdev"
	Option     "fbdev" "/dev/fb0"
EndSection

Section "Screen"
	Identifier "screen0"
	Device     "fb"
EndSection

Section "ServerLayout"
	Identifier "layout"
	Screen     "screen0"
EndSection

Section "Module"
	Load "fb"
    Load "fbdevhw"
	Load "libinput"
	Load "shadow"
	Load "shadowfb"
EndSection

Section "InputClass"
    Identifier "keyboard catchall"
    MatchIsKeyboard "on"
    MatchDevicePath "/dev/input/event*"
    Driver "libinput"
    Option "XkbLayout" "us"
EndSection
