Section "Device"
	Identifier "fb"
	Driver     "fbdev"
	Option     "fbdev" "/dev/fb0"
EndSection

Section "Screen"
	Identifier "screen0"
	Device     "fb"
EndSection

Section "ServerLayout"
	Identifier "layout"
	Screen     "screen0"
EndSection

Section "Module"
	Load "fb"
	Load "shadow"
	Load "shadowfb"
    Load "fbdevhw"
EndSection
