#!/usr/bin/env sh

case "$1" in
	start)
		for i in $(seq 0 8); do
			reset-fb $i
		done
		backlight on
		;;
	stop)
		backlight off
		;;
	restart)
		"$0" stop
		"$0" start
		;;
	usage)
		echo "$0 <start/stop/restart>"
		exit 1
		;;
esac
