#!/usr/bin/env sh

data_mountpoint="/data"

mount_data_partition() {
	if [ -b "$2" ]; then
		fsck.ext4 -n "$2" || init_data_partition "$2"
	else
		make_data_partition "$1" "$2"
	fi

	mount "$2" "$data_mountpoint"

	if [ ! -f "${data_mountpoint}/led-alarm.conf" ]; then
		cp "/etc/led-alarm-default.conf" "${data_mountpoint}/led-alarm.conf"
	fi

	ln -sf "${data_mountpoint}/led-alarm.conf" /var/run/led-alarm.conf
}

make_data_partition() {
	echo "Creating new data partition!"
	echo parted "$1" -s "mkpart primary ext4 512M 544M"
	parted "$1" -s "mkpart primary ext4 512M 544M"
	echo "fsck.ext4 -n "$2" || mkfs.ext4 -F "$2""
	fsck.ext4 -n "$2" || mkfs.ext4 -F "$2"
}
