#!/usr/bin/env sh

. "/usr/share/jlbsp/data-mount"

validate_led_alarm() {
	if [ ! -b "${2}1" ] || [ ! -b "${2}2" ] || [ -b "${2}4" ]; then
		echo "Fail - Missing / Unidentified partition on $1 device?!"
		return 1;
	fi
	# The third "schrödinger" partition may or may not exist
	# but on the original rootfs ONLY
	if [ "$1" != "orig" ] && [ -b "${2}3" ]; then
		echo "Fail - Data partition exists on $1 device?!"
		return 1
	fi
	echo "Custom validation for ${2}X partitions on $1 device passed."
	return 0
}

upgrade_start() {
	validate_func="validate_led_alarm"
}

upgrade_pre_unmount() {
	echo "Stopping processes"
	"/etc/init.d/S50lighttpd" stop
	"/etc/init.d/S95led-alarm" stop
	echo "Giving processes 1.5 seconds to gracefully stop"
	sleep 1.5
	echo "Unmounting data partition!"
	sync
	umount -f "$data_mountpoint"
}
