on:
  push:
    branches:
      - master
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: linux-amd64
    env:
      BSP_NAME: ntp
      SSH_OPTS: -oBatchMode=yes
      BR2_DL_DIR: /opt/act-runner-dl
      BR2_CCACHE_DIR: /opt/act-runner/ccache
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup BSP
        timeout: 30
        run: ./bsp setup "${BSP_NAME}"

      - name: Source BSP
        timeout: 120
        run: ./bsp source "${BSP_NAME}"

      - name: Build BSP
        timeout: 300
        run: ./bsp build "${BSP_NAME}" || support/ntfy "build" "Couldn't build BSP ${BSP_NAME}"

      - name: Deploy BSP
        timeout: 5
        run: ./bsp deploy "${BSP_NAME}" || support/ntfy "brick" "Bricked BSP ${BSP_NAME}"

      - name: Cleanup DL dir
        run: find "${BR2_DL_DIR}" -atime +30 -exec rm -v "{}" \;

      - name: Cleanup cache dir
        run: find "${BR2_CCACHE_DIR}" -atime +30 -exec rm -v "{}" \;
