# .github/workflow/build.yml

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Setup container
        run:  |
          apt-get update -y
          apt-get install -y fd-find ripgrep shellcheck
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build NTP server
        run: BUILDS_DIR=builds ./bsp build ntp tdisp
