# .github/workflow/shellcheck.yml

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  shellcheck:
    runs-on: archlinux-latest
    steps:
      - name: Setup container
        run:  pacman -S fd ripgrep shellcheck
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Recursively run shellcheck
        run: ./bsp shellcheck json

